name: GroupLock
version: 0.5
main: uk.co.jacekk.bukkit.grouplock.GroupLock
load: startup
commands:
    lock:
        usage: /<command> [<add/remove> <player_name>]
        description: Lock or unlock a block